name: super_stepper
description: A highly customizable animated Flutter stepper with controller support, builders, RTL, horizontal and vertical layouts.
version: 0.1.2
homepage: https://github.com/mustafaLzoghby/super_stepper
repository: https://github.com/mustafaLzoghby/super_stepper
issue_tracker: https://github.com/mustafaLzoghby/super_stepper/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
